base/urls.py
from django.conf.urls import url

from . import views

app_name = 'base'

urlpatterns = [
    #principal view
    url('index/', views.index, name='index'),

    #Forgot Password View
    url('forgot-password/', views.forgot_password, name='forgot_password'),

    #module users
    url('users/', views.users, name='users'),
    url('edit-user/(?P<id_user>[0-9]+)/$', views.edit_user, name='edit_user'),
    url('delete-user/(?P<id_user>[0-9]+)/$', views.delete_user, name='delete_user'),
    url('view-user/(?P<id_user>[0-9]+)/$', views.view_user, name='view_user'),

    #module enviroments
    url('enviroments/', views.enviroments, name='enviroments'),
    url('edit-enviroment/(?P<id_enviroment>[0-9]+)/$', views.edit_enviroment, name='edit_enviroment'),
    url('delete-enviroment/(?P<id_enviroment>[0-9]+)/$', views.delete_enviroment, name='delete_enviroment'),
    url('view-enviroment/(?P<id_enviroment>[0-9]+)/$', views.view_enviroment, name='view_enviroment'),

    #module category and subcategory
    url('category_subcategory/', views.category_subcategory, name='category_subcategory'),
    url('edit-enviroment/(?P<id_enviroment>[0-9]+)/$', views.edit_enviroment, name='edit_enviroment'),
    url('delete-enviroment/(?P<id_enviroment>[0-9]+)/$', views.delete_enviroment, name='delete_enviroment'),
    url('view-enviroment/(?P<id_enviroment>[0-9]+)/$', views.view_enviroment, name='view_enviroment'),

    #module subcategorytwo
    url('create_item/', views.create_item, name='create_item'),
    url('edit-item/(?P<id_item>[0-9]+)/$', views.edit_item, name='edit_item'),
    url('delete-item/(?P<id_item>[0-9]+)/$', views.delete_item, name='delete_item'),
    url('view-item/(?P<id_item>[0-9]+)/$', views.view_item, name='view_item'),

    #module subcategory
    url('create_subcategory/', views.create_subcategory, name='create_subcategory'),
    url('edit-subcategory/(?P<id_subcategory>[0-9]+)/$', views.edit_subcategory, name='edit_subcategory'),
    url('delete-subcategory/(?P<id_subcategory>[0-9]+)/$', views.delete_subcategory, name='delete_subcategory'),
    url('view_subcategory/(?P<id_subcategory>[0-9]+)/$', views.view_subcategory, name='view_subcategory'),

    #module category
    url('create_category/', views.create_category, name='create_category'),
    url('edit-category/(?P<id_category>[0-9]+)/$', views.edit_category, name='edit_category'),
    url('delete-category/(?P<id_category>[0-9]+)/$', views.delete_category, name='delete_category'),
    url('view_category/(?P<id_category>[0-9]+)/$', views.view_category, name='view_category'),

    #module type_measure
    url('create_type_measure/', views.create_type_measure, name='create_type_measure'),
    url('edit-typemeasure/(?P<id_type_measure>[0-9]+)/$', views.edit_type_measure, name='edit_type_measure'),
    url('delete-typemeasure/(?P<id_type_measure>[0-9]+)/$', views.delete_type_measure, name='delete_type_measure'),
    url('view_type_measure/(?P<id_type_measure>[0-9]+)/$', views.view_type_measure, name='view_type_measure'),

    # module material
    url('materials/', views.show_materials, name='show_materials'),
    url('create_material/', views.create_material, name='create_material'),
    url('edit-material/(?P<id_material>[0-9]+)/$', views.edit_material, name='edit_material'),
    url('delete-material/(?P<id_material>[0-9]+)/$', views.delete_material, name='delete_material'),
    url('view_material/(?P<id_material>[0-9]+)/$', views.view_material, name='view_material'),

    # module material enviroments
    url('material_enviroment/', views.material_environment, name='material_environment'),
    url('edit-material_environment/(?P<id_material_environment>[0-9]+)/$', views.edit_material_environment, name='edit_material_environment'),
    url('delete-material_environment/(?P<id_material_environment>[0-9]+)/$', views.delete_material_environment, name='delete_material_environment'),
    url('view_material_environment/(?P<id_material_environment>[0-9]+)/$', views.view_material_environment, name='view_material_environment'),

    # module contact
    url('create_contact/', views.create_contact, name='create_contact'),
    url('edit-contact/(?P<id_contact>[0-9]+)/$', views.edit_contact, name='edit_contact'),
    url('delete-contact/(?P<id_contact>[0-9]+)/$', views.delete_contact, name='delete_contact'),
    url('view_contact/(?P<id_contact>[0-9]+)/$', views.view_contact, name='view_contact'),

    #module providers
    url('providers/', views.show_providers, name='show_providers'),
    url('create_provider/', views.create_provider, name='create_provider'),
    url('edit-provider/(?P<id_provider>[0-9]+)/$', views.edit_provider, name='edit_provider'),
    url('delete-provider/(?P<id_provider>[0-9]+)/$', views.delete_provider, name='delete_provider'),
    url('view_provider/(?P<id_provider>[0-9]+)/$', views.view_provider, name='view_provider'),

    #module models
    url('create_model/', views.create_model, name='create_model'),
    url('edit-model/(?P<id_model>[0-9]+)/$', views.edit_model, name='edit_model'),
    url('delete-model/(?P<id_model>[0-9]+)/$', views.delete_model, name='delete_model'),
    url('view_model/(?P<id_model>[0-9]+)/$', views.view_model, name='view_model'),

    #module projects
    url('projects/', views.show_projects, name='show_projects'),


    #module wing
    url('create_wing/', views.create_wing, name='create_wing'),
    url('edit-wing/(?P<id_wing>[0-9]+)/$', views.edit_wing, name='edit_wing'),
    url('delete-wing/(?P<id_wing>[0-9]+)/$', views.delete_wing, name='delete_wing'),
    url('view_wing/(?P<id_wing>[0-9]+)/$', views.view_wing, name='view_wing'),

    #module building
    url('create_building/', views.create_building, name='create_building'),
    url('edit-building/(?P<id_building>[0-9]+)/$', views.edit_building, name='edit_building'),
    url('delete-building/(?P<id_building>[0-9]+)/$', views.delete_building, name='delete_building'),
    url('view_building/(?P<id_building>[0-9]+)/$', views.view_building, name='view_building'),

    #module floor
    url('create_floor/', views.create_floor, name='create_floor'),
    url('edit-floor/(?P<id_floor>[0-9]+)/$', views.edit_floor, name='edit_floor'),
    url('delete-floor/(?P<id_floor>[0-9]+)/$', views.delete_floor, name='delete_floor'),
    url('view_floor/(?P<id_floor>[0-9]+)/$', views.view_floor, name='view_floor'),

    # module apartment
    url('create_apartment/', views.create_apartment, name='create_apartment'),
    url('edit-apartment/(?P<id_apartment>[0-9]+)/$', views.edit_apartment, name='edit_apartment'),
    url('delete-apartment/(?P<id_apartment>[0-9]+)/$', views.delete_apartment, name='delete_apartment'),
    url('view_apartment/(?P<id_apartment>[0-9]+)/$', views.view_apartment, name='view_apartment'),

    # module state
    url('create_state/', views.create_state, name='create_state'),
    url('edit_state/(?P<id_state>[0-9]+)/$', views.edit_state, name='edit_state'),
    url('delete-state/(?P<id_state>[0-9]+)/$', views.delete_state, name='delete_state'),
    url('view_state/(?P<id_state>[0-9]+)/$', views.view_state, name='view_state'),

    # module macro schedule
    url('create_macro_schedule/', views.create_macro_schedule, name='create_macro_schedule'),
    url('delete-macro_schedule/(?P<id_macro_schedule>[0-9]+)/$', views.delete_macro_schedule, name='delete_macro_schedule'),
    url('view_macro_schedule/(?P<id_macro_schedule>[0-9]+)/$', views.view_macro_schedule, name='view_macro_schedule'),

    # module project
    url('create_project/', views.create_project, name='create_project'),
    url('edit-project/(?P<id_project>[0-9]+)/$', views.edit_project, name='edit_project'),
    url('delete-project/(?P<id_project>[0-9]+)/$', views.delete_project, name='delete_project'),
    url('view_project/(?P<id_project>[0-9]+)/$', views.view_project, name='view_project'),

]

lecesse/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from django.contrib.auth import views as auth_views

urlpatterns = [

    #direcciones del modulo base
    path('home', include('base.urls')),
    path('', RedirectView.as_view(url="/home/index/")),
    # muestra el login de inicio
	path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'),
        name='login'),
	#Logout
	path('logout/', auth_views.LogoutView.as_view(template_name='registration/login.html'),
        name='logout'),

]+ static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

base/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import ugettext_lazy as _
from base.choices import ROLE_CHOICES, IT_PROPOSE_CHOICES, TYPE_MATERIAL_CHOICES



class Environment(models.Model):
    name = models.CharField(max_length=100, null=False)
    description = models.CharField(max_length=150, null=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class SubcategoryTwo(models.Model):
    name = models.CharField(max_length=100, null=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Subcategory(models.Model):
    name = models.CharField(max_length=100, null=False)
    subcategory_two = models.ForeignKey(SubcategoryTwo, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=100, null=False)
    subcategory = models.ForeignKey(SubcategoryTwo, on_delete=models.CASCADE)
    enviroment = models.ForeignKey(Environment, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class TypeMeasure(models.Model):
    name = models.CharField(max_length=100, null=False)

    def __str__(self):
        return self.name


class Material(models.Model):
    name = models.CharField(max_length=100, null=False)
    description = models.CharField(max_length=200, null=False)
    image = models.ImageField(upload_to='material')
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    subcategory = models.ForeignKey(Subcategory, on_delete=models.CASCADE)
    subcategory_two = models.ForeignKey(SubcategoryTwo, on_delete=models.CASCADE)
    type_measure = models.ForeignKey(TypeMeasure, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.name)


class MaterialEnvironment(models.Model):
    type_material = models.CharField(max_length=200,choices=TYPE_MATERIAL_CHOICES, null=False)
    material_unity = models.CharField(max_length=100, null=False)
    unity_price = models.IntegerField(null=False)
    area_environment = models.IntegerField(null=False )
    total_price = models.IntegerField(null=True)
    is_proposal = models.CharField(max_length=100, choices=IT_PROPOSE_CHOICES ,null=False)
    environment = models.ForeignKey(Environment, on_delete=models.CASCADE)
    material = models.ForeignKey(Material, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.type_material)


class Contact(models.Model):
    first_name = models.CharField(max_length=100, null=False)
    last_name = models.CharField(max_length=100, null=False)
    position = models.CharField(max_length=100, null=False)
    phone_number = models.CharField(max_length=100, null=False)
    responsible_account = models.CharField(max_length=100, null=False)
    project_name = models.CharField(max_length=100, null=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.first_name


class Provider(models.Model):
    name = models.CharField(max_length=100, null=False)
    phone_number = models.CharField(max_length=100, null=False)
    email = models.CharField(max_length=100, null=False)
    address_company = models.CharField(max_length=200, null=False)
    activity = models.CharField(max_length=100, null=False)
    state = models.CharField(max_length=100, null=False)
    zip_code = models.CharField(max_length=100, null=False)
    contact = models.ForeignKey(Contact, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name



class Model(models.Model):
    name = models.CharField(max_length=100, null=False)
    image_flat = models.ImageField(upload_to='material')
    environment = models.ForeignKey(Environment, on_delete=models.CASCADE)
    environment_material = models.ForeignKey(MaterialEnvironment, on_delete=models.CASCADE)
    provider = models.ForeignKey(Provider, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Building(models.Model):
    number = models.IntegerField(null=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.number)


class Wing(models.Model):
    name = models.CharField(max_length=100, null=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.name)


class Floor(models.Model):
    number = models.IntegerField(null=False)
    building = models.ForeignKey(Building, on_delete=models.CASCADE)
    wing =  models.ForeignKey(Wing, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.number)


class MacroSchedule(models.Model):
    name = models.CharField(max_length=100, null=False)
    date_init = models.CharField(max_length=100, null=False)
    date_finish = models.CharField(max_length=100, null=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.name)


class Apartment(models.Model):
    number = models.IntegerField(null=False)
    floor = models.ForeignKey(Floor, on_delete=models.CASCADE)
    model = models.ForeignKey(Model, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.number)



class Project(models.Model):
    name = models.CharField(max_length=150, null=False)
    address = models.CharField(max_length=150, null=False)
    city = models.CharField(max_length=100, null=False)
    state = models.CharField(max_length=100, null=False)
    zip_code = models.CharField(max_length=100, null=False)
    owner_project = models.CharField(max_length=100, null=False)
    macro_schedule = models.OneToOneField(MacroSchedule, on_delete=models.CASCADE)
    contact_fk = models.ForeignKey(Contact, on_delete=models.CASCADE)
    building = models.ForeignKey(Building, on_delete=models.CASCADE)
    apartment = models.ForeignKey(Apartment, on_delete=models.CASCADE)
    floor = models.ForeignKey(Floor, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.name)


class CustomUser(AbstractUser):
    email = models.EmailField(_('email address'), unique=True)
    document_number = models.CharField(max_length=150, null=False)
    phone_number = models.CharField(max_length=30, null=False)
    address = models.CharField(max_length=100, null=False)
    role = models.CharField(max_length=30, choices=ROLE_CHOICES, null=False)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    username = None
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []


class State(models.Model):
    name = models.CharField(max_length=100, null=False)
    commentary = models.CharField(max_length=200, null=False)
    assessment = models.CharField(max_length=150, null=False)
    percentage = models.CharField(max_length=150, null=False)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    apartment = models.ForeignKey(Apartment, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.name)

base/templates/category_subcategory.html
{% extends 'base.html' %}
{% block content %}
<div class="">
            <!-- Content Header (Page header) -->
            <section class="content-header mb-4">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">

                        </div>
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="{% url 'base:index' %}">Home</a></li>
                                <li class="breadcrumb-item active">Category & subcategory</li>
                            </ol>
                        </div>
                    </div>
                </div><!-- /.container-fluid -->
            </section>

            <!-- Main content -->
            <section class="content">

                <!-- Default box -->
                <div>
                    <div class="card-body p-0">
                        <div class="row">
                            <div class="col-md-4 ">
                                <div class="row">
                                        <div class="col-sm-2"></div>
                                        <div class="col-sm-8 mt-3">
                                                <a href="{% url 'base:create_item' %}"><button type="button" class="btn btn-block btn-outline-secondary btn-lg" style="background-color:#ffffff;">Create Item</button></a>
                                                <br>
                                                <a href="{% url 'base:create_subcategory' %}"><button type="button" class="btn btn-block btn-outline-secondary btn-lg" style="background-color:#ffffff;">Create Subcategory</button></a>
                                                <br>
                                                <a href="{% url 'base:create_category' %}"><button type="button" class="btn btn-block btn-outline-secondary btn-lg" style="background-color:#ffffff;">Create Category</button></a>
                                        </div>
                                        <div class="col-sm-2"></div>
                                </div>
                            </div>
                            <div class="col-md-7">
                                <table class="table table-striped projects mt-3" style="background:#ffffff;">
                                    <thead>
                                        <tr>
                                            <th style="width: 5%">
                                                ID
                                            </th>

                                            <th style="width: 20%">
                                                Category
                                            </th>
                                            <th style="width: 20%">
                                                Subcategory
                                            </th>
                                            <th style="width: 20%">
                                                Environment
                                            </th>
                                            <th style="width: 25%">
                                            </th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                         {% for category in categories%}
                                        <tr>
                                            <td>
                                                {{forloop.counter}}
                                            </td>

                                            <td>
                                                <ul class="list-inline">
                                                    <li class="list-inline-item">
                                                        {{category.name}}
                                                    </li>

                                                </ul>
                                            </td>
                                            <td >
                                                {{category.subcategory.name}}
                                            </td>
                                            <td >
                                                {{category.enviroment.name}}
                                            </td>
                                            <td class="project-actions text-right">
                                                <a class="btn btn-primary btn-sm" href="{% url 'base:view_category' category.id  %}">
                                                    <i class="far fa-eye" style="color: #ffffff;"></i>
                                                </a>
                                                <a class="btn btn-info btn-sm" href="{% url 'base:edit_category' category.id  %}">
                                                    <i class="fas fa-pencil-alt" style="color: #ffffff;">
                                                    </i>
                                                </a>
                                                <a class="btn btn-danger btn-sm" href="{% url 'base:delete_category' category.id  %}">
                                                    <i class="fas fa-trash" style="color: #ffffff;">
                                                    </i>
                                                </a>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                                <div class="row">
                                    <div class="col-sm-12 col-md-12">
                                        <div class="dataTables_paginate paging_simple_numbers" id="example1_paginate">
                                            <ul class="pagination">
                                                <li class="paginate_button page-item previous disabled" id="example1_previous">
                                                    <a href="#" aria-controls="example1" data-dt-idx="0" tabindex="0" class="page-link">
                                                        Previous
                                                    </a>
                                                </li>
                                                <li class="paginate_button page-item active">
                                                    <a href="#" aria-controls="example1" data-dt-idx="1" tabindex="0" class="page-link">
                                                        1
                                                    </a>
                                                </li>
                                                <li class="paginate_button page-item ">
                                                    <a href="#" aria-controls="example1" data-dt-idx="2" tabindex="0" class="page-link">
                                                        2
                                                    </a>
                                                </li>
                                               <li class="paginate_button page-item next" id="example1_next">
                                                   <a href="#" aria-controls="example1" data-dt-idx="7" tabindex="0" class="page-link">
                                                       Next
                                                    </a>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-1"></div>
                        </div>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->

            </section>
            <!-- /.content -->
        </div>

{% endblock %}

base/templates/create_wing.html
{% extends 'base.html' %}
{% block content %}

<!-- Content Header (Page header) -->
<section class="content-header mb-4">
    <div class="container-fluid">
        <div class="row mt-5 mb-2">
            <div class="col-md-1 mt-4"></div>
            <div class="col-md-4 mt-4">

                <div class="callout callout-info">
                    <h4 class="modal-title text-center">Wing Create</h4>
                    <form role="form" method="POST">
                        {% csrf_token %}
                        <div class="card-body">
                            <div class="">
                                <div class="row">
                                    <div class="col-sm-1"></div>
                                    <div class="col-sm-10">
                                        <div class="form-group">
                                            <label for="exampleInputEmail1">Name</label>
                                            {{ form.name }}
                                        </div>

                                        <aside class="text-right">
                                            <button type="button" class="btn btn-danger mt-4"
                                                data-dismiss="modal">Cancel</button> <button type="submit"
                                                class="btn btn-primary ml-4 mt-4">Save</button>
                                        </aside>
                                    </div>
                                    <div class="col-sm-1"></div>

                                </div>

                            </div>
                        </div>

                    </form>
                </div>

            </div>
            <div class="col-md-1 mt-4"></div>
            <div class="col-md-4 mt-4">
                <table class="table table-striped projects mt-3" style="background:#ffffff;">
                    <thead>
                        <tr>
                            <th style="width: 5%">
                                ID
                            </th>

                            <th style="width: 30%">
                                Name
                            </th>
                            <th style="width: 35%">
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for wing in wings %}
                        <tr>
                            <td>
                                {{ forloop.counter}}
                            </td>

                            <td>
                                {{ wing.name}}
                            </td>
                            <td class="project-actions text-right">
                                <a class="btn btn-primary btn-sm" href="{% url 'base:view_wing' wing.id %}">
                                    <i class="far fa-eye" style="color: #ffffff;"></i>
                                </a>
                                <a class="btn btn-info btn-sm" href="{% url 'base:edit_wing' wing.id %}">
                                    <i class="fas fa-pencil-alt" style="color: #ffffff;">
                                    </i>
                                </a>
                                <a class="btn btn-danger btn-sm" href="{% url 'base:delete_wing' wing.id %}">
                                    <i class="fas fa-trash" style="color: #ffffff;">
                                    </i>
                                </a>
                            </td>
                        </tr>
                        {% endfor %}

                    </tbody>
                </table>
                <div class="row">
                    <div class="col-sm-12 col-md-12">
                        <div class="dataTables_paginate paging_simple_numbers" id="example1_paginate">
                            <ul class="pagination">
                                <li class="paginate_button page-item previous disabled" id="example1_previous">
                                    <a href="#" aria-controls="example1" data-dt-idx="0" tabindex="0" class="page-link">
                                        Previous
                                    </a>
                                </li>
                                <li class="paginate_button page-item active">
                                    <a href="#" aria-controls="example1" data-dt-idx="1" tabindex="0" class="page-link">
                                        1
                                    </a>
                                </li>
                                <li class="paginate_button page-item ">
                                    <a href="#" aria-controls="example1" data-dt-idx="2" tabindex="0" class="page-link">
                                        2
                                    </a>
                                </li>
                                <li class="paginate_button page-item next" id="example1_next">
                                    <a href="#" aria-controls="example1" data-dt-idx="7" tabindex="0" class="page-link">
                                        Next
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-2 mt-4"></div>
        </div>
    </div><!-- /.container-fluid -->
</section>

{% endblock %}

base/templates/edit_materials.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>